#
# Dockerfile for installing additional packages from source in ROS2
#
FROM dustynv/ros:humble-ros-base-l4t-r36.2.0

ARG ROS_PACKAGES \
    ROS_WORKSPACE=${ROS_ROOT}
    
RUN /ros2_install.sh rtabmap_ros realsense2_camera

